トップページに2021のティザーサイトへのリンクを追加
pyconjp/www.pycon.jp pull request #61
Opened 2021-05-05 14:39 UTC by k-nakamura

- トップページのPyCon JP 2021の項目に PyCon JP 2021ティザーサイトhttps://2021.pycon.jp へのリンクを追加

2021-05-05 14:40 UTC, k-nakamura commented
@ftnext からの依頼でプルリクエストを作成しました。

2021-05-05 15:07 UTC, ftnext requested changes
@k-nakamura 対応ありがとうございます。

MUSTの方は対応お願いします。
IMOの方は必須ではない（私はこう思う）なので、おまかせです

加えてもう1個（別のコメントで）修正をお願いします

2021-05-05 15:07 UTC, ftnext commented on source/index.rst
> +For the latest information for PyCon JP 2020, please visit `our Website <https://2021.pycon.jp/>`_ and `PyCon JP Blog <https://pyconjp.blogspot.com/search/label/pyconjp2021>`_ .
MUST: 2020になってますね。2021に修正お願いします

2021-05-05 15:07 UTC, ftnext commented on source/index.rst
> +詳細については `公式Webサイト <https://2021.pycon.jp/>`_ および `PyCon JP Blog <https://pyconjp.blogspot.com/search/label/pyconjp2021>`_ をご確認ください。
対応ありがとうございます

IMO（In my opinion）：
「PyCon JP 2021 の最新情報およびお問い合わせは 公式Webサイト および PyCon JP Blog をご確認ください。」
でもいいかなと思いました（リンクは省略しています）

2021-05-05 15:10 UTC, ftnext commented
@k-nakamura 私が伝え漏らしていました。申し訳ありません。
以下のの対応も合わせてお願いします。

27行目に
>PyCon JP 2021 のカンファレンス日程は2021/10/15-16に仮決定しました!

とありますが、「仮」がトレます。
合わせて、33行目の

>The schedule for PyCon JP 2021 has been tentatively set. Oct 15 to 16.

もtentativelyがトレます

FYI: https://github.com/pyconjp/pycon.jp.2021.teaser/issues/36

2021-05-06 11:05 UTC, k-nakamura commented on source/index.rst
> +詳細については `公式Webサイト <https://2021.pycon.jp/>`_ および `PyCon JP Blog <https://pyconjp.blogspot.com/search/label/pyconjp2021>`_ をご確認ください。
日本語の文言を「PyCon JP 2021 の最新情報およびお問い合わせは 公式Webサイト および PyCon JP Blog をご確認ください。」に変更し、それに沿って英語の文言も修正しました。

また、「PyCon JP 2021」の1つ下の項目が「お問い合わせ」となっていますが、

- PyCon JP 2021に関するお問い合わせは公式サイトまたはPyCon JP Blog
- 一般社団法人PyCon JP Associationへの問い合わせは理事メールアドレスにメール

の問い合わせ内容と経路の違いを明確にするため、「お問い合わせ」の項目を「一般社団法人PyCon JP Associationへのお問い合わせ」に変更するのはいかがでしょうか?

2021-05-06 11:05 UTC, k-nakamura commented on source/index.rst
> +For the latest information for PyCon JP 2020, please visit `our Website <https://2021.pycon.jp/>`_ and `PyCon JP Blog <https://pyconjp.blogspot.com/search/label/pyconjp2021>`_ .
PyCon JP 2020をPyCon JP 2021に修正しました。

2021-05-06 11:08 UTC, k-nakamura commented
日程の表記を以下の通り変更しました(それぞれ"仮"、"tentatively"を削除)。
- PyCon JP 2021 のカンファレンス日程は2021/10/15-16に決定しました!
- The schedule for PyCon JP 2021 has been set. Oct 15 to 16.

2021-05-07 08:12 UTC, k-nakamura commented on source/index.rst
> +詳細については `公式Webサイト <https://2021.pycon.jp/>`_ および `PyCon JP Blog <https://pyconjp.blogspot.com/search/label/pyconjp2021>`_ をご確認ください。
承知しました。このままにしておきます。

2021-05-07 17:15 UTC, ftnext approved these changes
LGTM

![多分動くと思うからリリースしようぜ](https://user-images.githubusercontent.com/21273221/117485305-31810080-afa3-11eb-8192-52c941b3fa28.jpg)

対応ありがとうございます

2021-05-07 17:15 UTC, merged